In [1]:
import numpy as np

In [6]:
x = np.random.rand(2,4)

In [7]:
print(x)

[[ 0.6434379   0.43554111  0.55090622  0.90453682]
 [ 0.03495108  0.35478044  0.06795655  0.50296527]]


In [8]:
print(x + 1)

[[ 1.6434379   1.43554111  1.55090622  1.90453682]
 [ 1.03495108  1.35478044  1.06795655  1.50296527]]


In [9]:
a = np.array([[11,12,13,14,15,16], [17,18,19,20,21,22]])

In [10]:
print(a)

[[11 12 13 14 15 16]
 [17 18 19 20 21 22]]


In [11]:
a.ravel()

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])