In [3]:
import numpy as np

In [4]:
from time import time

In [16]:
def incrembyone(x):
    return x + 1

In [6]:
data_array = np.linspace(1, 5, 1000000)

In [7]:
t1 = time()

In [8]:
len_data = len(data_array)

In [9]:
print('Len = ', str(len_data))

Len =  1000000


In [10]:
print(data_array[1:7])

[ 1.000004  1.000008  1.000012  1.000016  1.00002   1.000024]


In [11]:
for i in range(len_data):
    data_array[i] += 1

In [14]:
print('time for loop (No vectorization) -> '+ str(time() - t1))

time for loop (No vectorization) -> 128.9897699356079


In [15]:
t2 = time()

In [17]:
vecincr = np.vectorize(incrembyone)
vecincr(data_array)

array([ 3.      ,  3.000004,  3.000008, ...,  6.999992,  6.999996,  7.      ])

In [18]:
print('time for vectorized version-1 : ' + str(time() - t2))

time for vectorized version-1 : 117.07969927787781


In [22]:
t3 = time()

In [23]:
data_array += 1

In [24]:
print(data_array[1:7])

[ 4.000004  4.000008  4.000012  4.000016  4.00002   4.000024]


In [25]:
print('time for vectorized version=2 : ' + str(time() - t3))

time for vectorized version=2 : 0.5289499759674072


In [27]:
import math
fastsin = math.sin

In [33]:
x = list(range(1000000))
for i in x:
    x[i] = fastsin(x[i])

In [34]:
x

[0.0,
 0.8414709848078965,
 0.9092974268256817,
 0.1411200080598672,
 -0.7568024953079282,
 -0.9589242746631385,
 -0.27941549819892586,
 0.6569865987187891,
 0.9893582466233818,
 0.4121184852417566,
 -0.5440211108893699,
 -0.9999902065507035,
 -0.5365729180004349,
 0.4201670368266409,
 0.9906073556948704,
 0.6502878401571169,
 -0.2879033166650653,
 -0.9613974918795568,
 -0.750987246771676,
 0.14987720966295234,
 0.9129452507276277,
 0.836655638536056,
 -0.008851309290403876,
 -0.8462204041751706,
 -0.9055783620066239,
 -0.13235175009777303,
 0.7625584504796028,
 0.956375928404503,
 0.27090578830786904,
 -0.6636338842129675,
 -0.9880316240928618,
 -0.404037645323065,
 0.5514266812416906,
 0.9999118601072672,
 0.5290826861200238,
 -0.428182669496151,
 -0.9917788534431158,
 -0.6435381333569994,
 0.2963685787093853,
 0.9637953862840878,
 0.7451131604793488,
 -0.158622668804709,
 -0.9165215479156338,
 -0.8317747426285983,
 0.017701925105413577,
 0.8509035245341184,
 0.9017883476488092,
 0.1