In [1]:
import numpy as np

In [2]:
def addition(x, y, z):
    return x + y + z

In [16]:
def addploy():
    i = np.random.randint(25)
    poly1 = np.arange(i, i + 10)
    i = np.random.randint(25)
    poly2 = np.arange(i, i + 10)
    poly3 = np.arange(10, 20)
    print(poly1)
    print(poly2)
    print(poly3)
    print('-' * 32)
    vecf = np.vectorize(addition)
    print(vecf(poly1, poly2, poly3))

In [17]:
addploy()

[15 16 17 18 19 20 21 22 23 24]
[22 23 24 25 26 27 28 29 30 31]
[10 11 12 13 14 15 16 17 18 19]
--------------------------------
[47 50 53 56 59 62 65 68 71 74]


In [18]:
def posquare(x):
    if x > 0 :
        return x ** 2
    else:
        return -x

In [19]:
i = np.random.randint(25)
poly1 = np.arange(i, i+10)
print(poly1)

[11 12 13 14 15 16 17 18 19 20]


In [24]:
vecfunc = np.vectorize(posquare, otypes=[float])

In [25]:
vecfunc(poly1)

array([ 121.,  144.,  169.,  196.,  225.,  256.,  289.,  324.,  361.,  400.])